### ISSUE TITLE
拽入甬道bpmn:Participant后，其他节点拖拽报错

### ISSUE THREAD

**Issue by hakumen** [miyuesc/bpmn-process-designer#27]
拽入甬道后，其他节点拖拽报错
![企业微信20220107-101119](https://user-images.githubusercontent.com/14213802/148480187-c7e16baa-e95b-48f8-9b77-aeccbf2bb966.png)

甬道添加子甬道时也会报错
![企业微信截图_def68714-b120-4208-a15a-9ecbd98f4b1a](https://user-images.githubusercontent.com/14213802/148480205-b82ff5a0-8802-4cf1-b097-5bede65d7991.png)

**Comment by miyuesc** [comment]
![image](https://user-images.githubusercontent.com/50617660/148484535-d961ca69-929d-404d-9518-2bbc60861970.png)


报错？
