### ISSUE TITLE
2个任务之间可以有多条连线

### ISSUE THREAD

**Issue by WenZhiYong** [miyuesc/bpmn-process-designer#29]
2个任务之间存在多条连线 这种也是允许的吗，若想要限制该如何解决呢
<img width="475" alt="image" src="https://user-images.githubusercontent.com/19319178/155919137-936c23e9-074d-499d-8f16-90b8e7f6d869.png">

**Comment by miyuesc** [comment]
本身是没有限制规则的，你需要自定义一个连线规则
