### ISSUE TITLE
请教边界事件之类的扩展问题

### ISSUE THREAD

**Issue by andyqier88** [miyuesc/bpmn-process-designer#32]
大佬好，想咨询个问题，我想扩展下图的一个场景，该怎么扩展呢，跟issues #31 实现不太一样
<img width="388" alt="1648432127(1)" src="https://user-images.githubusercontent.com/10238991/160313058-7731595a-8cd2-4b88-b1da-81b51a686aa2.png">
截图来自Camunda Modeler
此节点的XML文件如下：
`<bpmn:boundaryEvent id="Event_1i22ehq" attachedToRef="Activity_1pv2sy7">

      <bpmn:timerEventDefinition id="TimerEventDefinition_0demg1p">

        <bpmn:timeDate xsi:type="bpmn:tFormalExpression">xx</bpmn:timeDate>

      </bpmn:timerEventDefinition>

    </bpmn:boundaryEvent>`
我曾尝试通过`window.bpmnInstances.moddle.create("bpmn:boundaryEvent")` 或者`window.bpmnInstances.moddle.create("bpmn:timerEventDefinition")`这种方式创建
报错如下图
![image](https://user-images.githubusercontent.com/10238991/160314001-190129fb-678c-4e7b-b752-c408c62ff9e7.png)

`"Error: unknown type <bpmn:boundaryEvent>"`

**Comment by andyqier88** [comment]
对比bpmn-moddle里的json文件，貌似在`package\designer\plugins\descriptor\camundaDescriptor.json`少了对TimerEventDefinition的描述，加上之后`window.bpmnInstances.modeling.updateModdleProperties`更新属性XML没有变化
`{
      "name": "TimerEventDefinition",
      "superClass": [
        "EventDefinition"
      ],
      "properties": [
        {
          "name": "timeDate",
          "type": "Expression",
          "xml": {
            "serialize": "xsi:type"
          }
        },
        {
          "name": "timeCycle",
          "type": "Expression",
          "xml": {
            "serialize": "xsi:type"
          }
        },
        {
          "name": "timeDuration",
          "type": "Expression",
          "xml": {
            "serialize": "xsi:type"
          }
        }
      ]
    }`

**Comment by andyqier88** [comment]
论坛里有一个类似场景的，但是没解决问题
[https://forum.bpmn.io/t/cannot-create-bpmn-timedate-within-intermediatecatchevent/3132](url)

**Comment by miyuesc** [comment]
> 我曾尝试通过window.bpmnInstances.moddle.create("bpmn:boundaryEvent") 或者window.bpmnInstances.moddle.create("bpmn:timerEventDefinition")这种方式创建

创建新元素或者属性时，传递的类型名参数应该是大写驼峰形式，比如 `moddle.create("bpmn:BoundaryEvent")` 。

另外，如果属性与该项目中的 descriptor.json 内的描述不一致，可以更新为你需要的格式，或者重新添加新的描述文件来对原有类型进行补充说明。

**Comment by miyuesc** [comment]
xml 描述文件规则可以看这个 https://juejin.cn/post/6912331982701592590 。你可以通过原生的 camunda 侧边栏编辑对应属性，之后查看元素的 businessObject 属性对象。对内部的每一个原型为 ModdleElement 的属性，都需要通过 moddle.create 进行创建，之后再更新到目标元素上

**Comment by andyqier88** [comment]
谢谢大兄弟，已赞赏~

**Comment by miyuesc** [comment]
😊谢谢
