### ISSUE TITLE
请教一下是否能进入折叠子流程

### ISSUE THREAD

**Issue by duwei54** [miyuesc/bpmn-process-designer#33]
RT. 在bpmnjs中右下角有个箭头可以进入折叠子流程. 但是这边好像没看到

**Comment by miyuesc** [comment]
请截图

**Comment by duwei54** [comment]
![bpmnjs](https://user-images.githubusercontent.com/8448880/161188092-281261dc-2fe0-4c94-9b13-6bac29b43ea3.png)
bpmnjs 的折叠子流程
![process-designer](https://user-images.githubusercontent.com/8448880/161188390-094f954d-e48c-4b29-a491-c7a8ed4e5ef6.jpg)
process-designer的折叠子流程

**Comment by miyuesc** [comment]
这个是 bpmn.js version 9 的一个新功能，具体信息可以看 https://bpmn.io/blog/posts/2022-bpmn-js-900-collapsed-subprocesses.html

**Comment by duwei54** [comment]
嗯嗯, 大佬有升级的计划嘛 😂

**Comment by miyuesc** [comment]
暂时不会考虑升级这个了哈

**Comment by duwei54** [comment]
嗯嗯好呢
