### ISSUE TITLE
请问大佬可以出一个vue3.0 + element-plus版本的吗?

### ISSUE THREAD

**Issue by kuaifengle** [miyuesc/bpmn-process-designer#44]
请问大佬可以出一个vue3.0 + element-plus版本的吗?

**Comment by miyuesc** [comment]
额。。。你看 readme 应该知道有一个 vue 3 版本的，只是没有用 eleme 了

**Comment by ifzm** [comment]
大佬 Vue3.0 的代码不开源吗，想学习下 @miyuesc

**Comment by miyuesc** [comment]
> 大佬 Vue3.0 的代码不开源吗，想学习下 @miyuesc

暂时不考虑开源了，用爱发电遭不住🌚🌚
