### ISSUE TITLE
元素的ID属性无法更改

### ISSUE THREAD

**Issue by MasterLover** [miyuesc/bpmn-process-designer#5]
目前看元素以及流程图的定义ID都是自动生成的,且无法更改.
但实际使用场景可能是自定义输入的所以看有没有啥办法更改

**Comment by miyuesc** [comment]
流程图的id在初始化的时候可以传入参数来改变，但是需要以字母作为开头。
至于在编辑过程中修改id，可能会造成选中异常的问题，，，这个我可以研究一下
