### ISSUE TITLE
重构的v2分支版本，用户任务该怎么添加节点审批用户呢

### ISSUE THREAD

**Issue by zukxu** [miyuesc/bpmn-process-designer#50]
重构的v2分支版本，用户任务该怎么添加节点审批用户呢
而且用户任务也没有任务监听器，只有执行监听器
如何在用户任务上挂载外部表单呢？
![image](https://user-images.githubusercontent.com/63381545/196603444-3fc2d888-a1ae-4844-8914-733b94cd0ce5.png)

如何在事件组件上添加条件，例如定时事件等？
如何在服务任务上添加指定需要执行的服务属性呢？
能出一期操作文档吗？

**Comment by miyuesc** [comment]
见掘金专栏 https://juejin.cn/column/6964382482007490590
