### ISSUE TITLE
数据回显问题  字体样式出现问题  鼠标移入流程图 又恢复了  请问是什么问题

### ISSUE THREAD

**Issue by mjlxiaoma** [miyuesc/bpmn-process-designer#53]

**Comment by miyuesc** [comment]
截图

**Comment by mjlxiaoma** [comment]
![1681006584356](https://user-images.githubusercontent.com/89441679/230750766-42996fc0-3bbf-4987-870e-962285174e06.jpg)
![1681006584350](https://user-images.githubusercontent.com/89441679/230750769-f0a53a40-9862-4fe5-b32c-470404dabc6b.jpg)
![1681006584361](https://user-images.githubusercontent.com/89441679/230750771-b99dbaad-431b-42fa-bc05-2ca8261ee041.jpg)
这个是步骤  编辑 显示异常 再到鼠标操作恢复正常

**Comment by miyuesc** [comment]
可能是版本问题，没有复现。建议升级 bpmn 相关版本
