### ISSUE TITLE
流程引擎选择了 flowable 但是导出的json文件 没有变化, 请楼主看过来

### ISSUE THREAD

**Issue by yangxianpei** [miyuesc/bpmn-process-designer#55]
如题

**Comment by miyuesc** [comment]
特殊属性才会有 flowable 前缀，例如
![image](https://github.com/miyuesc/bpmn-process-designer/assets/50617660/85a8e88d-c624-4c75-9121-9005cd840f43)
![image](https://github.com/miyuesc/bpmn-process-designer/assets/50617660/0a4b2852-058a-4eb5-a884-09136947548a)
