### ISSUE TITLE
你好我刚启动的时候爆Process is missing end event Process is missing start event Process is missing task node 进程缺少结束事件进程缺少开始事件进程缺少任务节点。

### ISSUE THREAD

**Issue by SilenceYangGao** [miyuesc/bpmn-process-designer#58]
![1690362125821](https://github.com/miyuesc/bpmn-process-designer/assets/40689838/b71be354-417d-451c-8690-a7da6256ca8c)  

虽然功能都是完好的，但是这个东西很难受一直想去掉，请问大佬有遇到我这样的嘛，要怎么解决

**Comment by miyuesc** [comment]
#16 参考该 issue 回复
