### ISSUE TITLE
并行为什么一定要有两个呢，'Flow splits implicitly': '流隐式拆分',

### ISSUE THREAD

**Issue by Abilish** [miyuesc/bpmn-process-designer#60]
并行网关为什么一定要有两个呢？只有一个为什么会报错，'Flow splits implicitly': '流隐式拆分',

![image](https://github.com/miyuesc/bpmn-process-designer/assets/77315426/79355354-926e-4bac-b9d1-7d993f8c803e)

![image](https://github.com/miyuesc/bpmn-process-designer/assets/77315426/9704237b-748e-4f7b-8245-aafdb38e7de0)

**Comment by miyuesc** [comment]
bpmnlint 默认的规则问题，开始节点一般只有一个出口

**Comment by Abilish** [comment]
> bpmnlint 默认的规则问题，开始节点一般只有一个出口

您好，请问任务也是只有一个出口吗，那么只有网关才允许多个输入，多个输出吗

**Comment by miyuesc** [comment]
@Abilish 任务可以有多个输出，但是需要设置每个出口的流转条件
