### ISSUE TITLE
请问如何删除Palette中不需要的工具

### ISSUE THREAD

**Issue by wjw020206** [miyuesc/bpmn-process-designer#63]
如下图这几个工具我都不需要，请问如何删除，我在代码中似乎并没有找到可以删除这几个工具的地方
<img width="113" alt="image" src="https://github.com/miyuesc/bpmn-process-designer/assets/59106659/3ed46542-2315-406e-88c6-76a520d34029">

**Comment by miyuesc** [comment]
css 隐藏或者重写 palette 覆盖

**Comment by wjw020206** [comment]
> css 隐藏或者重写 palette 覆盖

好的，感谢前辈的回复 :thumbsup:
