### ISSUE TITLE
Conversion from generic bpmn to flowable

### ISSUE THREAD

**Issue by marijap5** [miyuesc/bpmn-process-designer#66]
Hi,
Kudos for your great work! We are trying to convert this solution to Angular. We deeply analyzed your code, but we have one confusion. How does the conversion from generic bpmn to flowable happen?
![image](https://github.com/miyuesc/bpmn-process-designer/assets/138588973/1b4cbc42-faf5-45bd-90d5-21deeffc467a)
 *The flowable.json file is also provided as flowable descriptor, but when we export the diagram it is being exported and created as a generic bpmn. This is our saveXML code:
![image](https://github.com/miyuesc/bpmn-process-designer/assets/138588973/5d9bee5c-6de1-493c-817f-09af13731812)

**Comment by miyuesc** [comment]
Sorry, my English is not very good, so these contents are from translation software.

In bpmn-js, the basic BPMN2.0 specification is provided by default, which is in [bpmn-moddle](https://github.com/bpmn-io/bpmn-moddle).

At the same time, `BpmnPropertiesProviderModule` will only provide some basic properties that comply with the BPMN specification.

These properties are reflected in xml as 'bmn:xxx', or there is no 'bpmn:' part.

If you need to use flowable, you can learn about it according to the property panel of the [Camunda platform](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/main/src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js).
