### ISSUE TITLE
为何没有截图中的表单与监听器选项

### ISSUE THREAD

**Issue by MrLucy** [miyuesc/bpmn-process-designer#8]
大佬  为何定义了两个右侧面板，且demo直接采用的是没有监听器和表单选项的面板？是没有整合还是需要一些配置？

**Comment by miyuesc** [comment]
- 因为之前的版本存在比较严重的bug，所以迭代了新的版本。

- 目前增加了流程的全局信号和消息定义，以及部分任务节点的配置

- 监听器、表单、扩展属性后面会重新维护上去。

> 如果要使用监听器与表单的话，可以使用 package/process-penal/ProcessPenal.vue

**Comment by MrLucy** [comment]
好的，关注下 最近需要用到这种东西，做后台的，自己捣鼓这个有点麻烦。对比了几个发现您这个这几的比较好

假如现在我做个Tab来回切换两个自定义面板来去定义流程会有什么问题吗？
刚才大体看了下生成的xml文件  好像没发现什么问题   没有部署测试
